# @package _global_

defaults:
  - classification_base

dataset:
  name: swissprot_comet
  simple_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

  set_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

backbone:
  _target_: backbones.fcnet.EnFCNet

concept_mask:
  _target_: datasets.prot.concept_gen.PCAConcepts
  n_concepts: 8
  data_path: data/comet/swissprot/SP_PCA_components.pt
  n_feats: 2866
  top_k: 400


# For baseline, how many total classes
train_classes: 59

n_way: 5
n_shot: 5
n_query: 16