# @package _global_

defaults:
  - classification_base

dataset:
  name: tabula_muris_comet
  simple_cls:
    _target_: datasets.cell.tabula_muris.TMSimpleDataset

  set_cls:
    _target_: datasets.cell.tabula_muris.TMSetDataset

backbone:
  _target_: backbones.fcnet.EnFCNet

concept_mask:
  _target_: datasets.cell.concept_gen.PCAConcepts
  n_concepts: 8
  data_path: data/comet/tabula_muris/TM_PCA_components.pt
  n_feats: 2866
  top_k: 400
  type: original_comet


# For baseline, how many total classes
train_classes: 59

n_way: 5
n_shot: 5
n_query: 16