defaults:
  - dataset: tabula_muris_comet
  - method: comet

model: EnFCNet
n_way: 5
n_shot: 5
n_query: 16

mode: train

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
lr: 0.001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

wandb:
  project: "DL4BM"
  entity: "jcoldenhoff"
  mode: "online" # Can set to offline, disabled

iter_num: 600
